### ISSUE TITLE
Insert/update improvement ?

### ISSUE THREAD

**Issue by tontof** [TomBZombie/Maphper#12]
I was wondering if there is a way to improve performance for insert/update. For mysql and sqlite it tries to insert and if it fails, it tries to update. Most of the time from the mapper we can guess if it's a new or already existed item checking if primary key is set ? Why not testing that to ask for an insert or update query ? There could be one problem if user sets primary key manually: mapper will think it's an update instead of insert, but for that particular case the update query will fail and so we can perform an insert query after the fail.

**Comment by TomBZombie** [comment]
That's a good point and it would be worth benchmarking. We can only assume that when the primary key is null then it's new when auto_increment is used.

I'm not sure whether there would be a performance gain because for mysql at least you have to consider the speed difference between:

ON DUPLICATE KEY UPDATE and two trips to the database/generating two different queries.


Another alternative is REPLACE INTO but that causes a fairly significant set of problems due to being a DELETE/INSERT essentially.

**Comment by tontof** [comment]
I don't think the REPLACE INTO is really a good alternative too.

I guess there is no best solution for every case as it will mainly depend on application use.

For me, most of the time, the id will be an auto increment field and the approach of insert if null key and update if not (and insert if it fails) is a better approach. But that's for this particular case where id is auto increment. If not I suppose 'on duplicate key' is a better approach.

**Comment by TomBZombie** [comment]
It also depends on whether the table is going to have more inserts or updates or visa-versa. Things such as user details, blog posts and at the top extreme logging tables (Which never have an UPDATE call) tend to have more inserts than updates (in large systems users make more posts than they edit, users register more frequently than they change their login details, etc)...

**Comment by TomBZombie** [comment]
(on a different but related note, I'm going to add an option to maphper to use UUIDs instead of auto_increment as an option .. see http://blog.codinghorror.com/primary-keys-ids-versus-guids/ for mroe info )

**Comment by tontof** [comment]
I guess that adding primary key to insert interface solve the problem as it's possible to check if key is set or not. It's up to the adapter to change the behavior now !
For the uuid, I do not really use it but I think it could be great depending on application use.
