### ISSUE TITLE
Many to Many relationships

### ISSUE THREAD

**Issue by TomBZombie** [TomBZombie/Maphper#20]
Currently maphper supports n:n relationships in the same way as a relational database, you need an intermediate table to store the details about the relationship.

For example if you have a bank account and a customer where the customer can have many accounts and the account can be accessed by more than one person you would create (or have maphper create) a table called account_customer with the tables accountId and customerId.
```php
//mappers for each table
$accCustomer = new \Maphper\Maphper(new \Maphper\DataSource\Database($pdo, 'account_customer'));
$customers = new \Maphper\Maphper(new \Maphper\DataSource\Database($pdo, 'customer'));
$accounts = new \Maphper\Maphper(new \Maphper\DataSource\Database($pdo, 'account'));

//The customers -> account_customers mapper 
$customers->addRelation('accounts', new \Maphper\Relation(\Maphper\Relation::MANY, $accCustomer, 'id', 'customerId'));

//The account_customers -> account relationship
$accCustomer->addRelation('account', new \Maphper\Relation(\Maphper\Relation::ONE, $accounts, 'accountId', 'id'));

//The account_customers -> customer relationship
$accCustomer->addRelation('customer', new \Maphper\Relation(\Maphper\Relation::ONE, $customers, 'customerId', 'id'));

//The customers -> account_customer relationship
$accounts->addRelation('customers', new \Maphper\Relation(\Maphper\Relation::MANY, $accCustomer, 'id', 'accountId'));
```

Then you can get all customers accounts using:
```php
foreach ($customer[123]-accounts as $account) {
  echo $account->account->deposit;
}
```

Clearly this syntax isn't ideal and I'd like to make some way of signalling the relationship as a forward when creating it e.g.

```php
$customers->addRelation('accounts', new \Maphper\Relation(\Maphper\Relation::MANY, $accCustomer, 'id', 'customerId') , 'account');
```
which would automatically traverse the result object based on the third parameter. Although I'm not sure this is the best way to do it. It would be nicer to be able to do it behind the scenes so that as the user you don't have to know about or explicitly define the intermediate table... but this has several potential issues, especially since Maphper shouldn't assume that you're creating a relationship between two database tables.

happy to hear suggestions on how this can be resolved.

**Comment by garrettw** [comment]
For some reason I always thought the whole idea of intermediate tables was a MySQL kludge to emulate foreign keys. I assume that's not quite the case?

**Comment by TomBZombie** [comment]
Not at all. Consider tables `movie` and `actor` an actor can be in more than one movie and a movie has more than one actor it's impossible to do this with 2 tables and primary keys.

**Comment by garrettw** [comment]
Ah ok. I looked up more info about foreign keys and learned they're only for one-to-many relationships. I understand now.

**Comment by TomBZombie** [comment]
I've added a preliminary implementation for this. See the new unit tests for examples. This may not be the final implementation so I'm not adding the docs for it yet but it works like this:

(Same `actor`/`movie` relationship)

First set up the intermediate table (in this case I'm calling it `cast`) note that the primary key must be the two join fields for the intermediate table, so the `cast` table is a table with fields `actorId` and `movieId` to model which actor is in which movies (and at the same time, which movies have which actors)

```php
/Intermediate table (maphper can create this by itself with editmode = true, of course)
$cast = new \Maphper\Maphper(new \Maphper\Datasource\Database($pdo, 'cast', ['movieId', 'actorId']));
```
Then the maphper instances for the `movie` and `actor` tables as normal:

```php
$actors = new \Maphper\Maphper(new \Maphper\Datasource\Database($pdo, 'actor', 'id'));
$movies = new \Maphper\Maphper(new \Maphper\Datasource\Database($pdo, 'actor', 'id'));
```

There's  new relation type called MANY_MANY. Firstly set up the relationship between `actor` and `movie` I want the property to be called `movies` so that's the first parameter. Note that with a MANY_MANY relationship the third parameter is an array of mappers. It must be two mappers, the first is the intermediate join table and the second is the table being joined to. In this example I'm joining `$movies` to `$actors` via `$cast`

```php
$actors->addRelation('movies', new \Maphper\Relation(\Maphper\Relation::MANY_MANY, [$cast, $movies], 'id', 'movieId'));
```

I can now add an actor as normal:

```php
$actor = new stdclass;
$actor->name = 'Samuel L. Jackson';

$actors[] = $actor;
```

However, as a `movies` relationship has been set up I can now add some movies to the actor:

```php
$movie = new stdClass;
$movie->title = 'Pulp Fiction';
$actor->movies[] = $movie;

$movie = new stdClass;
$movie->title = 'Snakes on a Plane';
$actor->movies[] = $movie;
```

Assuming $actor was the first record, I can now get the actor's movies by:

```php
$actor = $actors[1];

echo $actor->name . ' was in the movies: ';
foreach ($actor->movies as $movie) {
    echo $movie->title . '<br />';
}
```

Of course, this is already possible with a 1:many relationship. A Many:Many relationship supports the inverse relationship... let's add another actor:

```php
$actor = new stdclass;
$actor->name = 'John Travolta';

$movie = $movies->filter(['title' =>'Pulp Fiction'])->item(0);
$actor->movies[] = $movie;
```

Now I can set up the inverse relationship so that a movie has a list of actors. Again, mapping to `$cast` and `$actors`:

```php
$movies->addRelation('actors', new \Maphper\Relation(\Maphper\Relation::MANY_MANY, [$cast, $actors], 'id', 'actorId'));
```

```php
$movie = $movies->filter(['title' =>'Pulp Fiction'])->item(0);
foreach ($movie->actors as $actor) {
echo $actor->name . '<br />';
}
```

Which should give Samuel L Jackson and John Travolta
